### ISSUE TITLE
Build failure on Ubuntu 22.04

### ISSUE THREAD

**Issue by glennklockwood** [breuner/elbencho#40] opened 2023-04-14 00:29 UTC
I am trying to build elbencho (version 72261d874cb3a81d1572a244d615fe9813cab337) on Ubuntu 22.04 and followed the README's instructions on installing dependencies.  When I build though, I hit this error:

```
glock@glocknode:~/elbencho$ make
[OPT] CUFILE (GDS) support disabled
[OPT] CUDA support disabled
[OPT] S3 support disabled. (Enable via S3_SUPPORT=1)
[OPT] mimalloc disabled
[OPT] Alternative HTTP service disabled
[OPT] HDFS support disabled
[DEP] source/Statistics.d
[CXX] source/Statistics.o
In file included from source/workers/Worker.h:5,
                 from source/workers/WorkerManager.h:4,
                 from source/Statistics.h:7,
                 from source/Statistics.cpp:8:
./source/LatencyHistogram.h:40:22: error: ‘atomic_uint64_t’ in namespace ‘std’ does not name a type
   40 |                 std::atomic_uint64_t numStoredValuesLive{0}; // for live stats
      |                      ^~~~~~~~~~~~~~~
./source/LatencyHistogram.h:41:22: error: ‘atomic_uint64_t’ in namespace ‘std’ does not name a type
   41 |                 std::atomic_uint64_t numMicroSecsTotalLive{0}; // for live stats
      |                      ^~~~~~~~~~~~~~~
./source/LatencyHistogram.h: In member function ‘void LatencyHistogram::addLatency(uint64_t)’:
./source/LatencyHistogram.h:48:25: error: ‘numStoredValuesLive’ was not declared in this scope; did you mean ‘numStoredValues’?
   48 |                         numStoredValuesLive++;
      |                         ^~~~~~~~~~~~~~~~~~~
      |                         numStoredValues
./source/LatencyHistogram.h:49:25: error: ‘numMicroSecsTotalLive’ was not declared in this scope; did you mean ‘numMicroSecTotal’?
   49 |                         numMicroSecsTotalLive += latencyMicroSec;
      |                         ^~~~~~~~~~~~~~~~~~~~~
      |                         numMicroSecTotal
./source/LatencyHistogram.h: In member function ‘void LatencyHistogram::addAndResetAverageLiveMicroSec(uint64_t&, uint64_t&)’:
./source/LatencyHistogram.h:81:47: error: ‘numStoredValuesLive’ was not declared in this scope; did you mean ‘numStoredValues’?
   81 |                         outNumStoredValues += numStoredValuesLive;
      |                                               ^~~~~~~~~~~~~~~~~~~
      |                                               numStoredValues
./source/LatencyHistogram.h:82:49: error: ‘numMicroSecsTotalLive’ was not declared in this scope; did you mean ‘numMicroSecTotal’?
   82 |                         outNumMicroSecsTotal += numMicroSecsTotalLive;
      |                                                 ^~~~~~~~~~~~~~~~~~~~~
      |                                                 numMicroSecTotal
make: *** [Makefile:219: source/Statistics.o] Error 1
```

Is there something new about compiler strictness or default C++ standard that changed in 22.04 that may have broken something here?

**Comment by breuner** [comment] 2023-04-14 18:41
Thanks a lot for reporting this, @glennklockwood . So much for me thinking that everything is fine when all the builds on docker hub (which include Ubuntu 22.04) complete. Turns out this was caused by a missing "#include <atomic>", but it's only missing when building without S3 support.

I just pushed the fix to github a few minutes ago, thus I'm closing this as resolved. But of course please re-open if there is still a problem.

**Closed by breuner** 2023-04-14 18:41 UTC
Labels: bug
